[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-gtk-greeter
autologin-user=ares
autologin-user-timeout=0
autologin-session=ares-kiosk
user-session=ares-kiosk
allow-guest=false
greeter-hide-users=true
greeter-show-manual-login=false
xserver-command=X -core -nolisten tcp
